language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-22

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-x86-android-17


#1) Install "apt addons"
#2) "before_install"
#3) "install"
#4) "before_script"
#5) "script"
#6) "after_success" or "after_failure"
#7) OPTIONAL "before_deploy"
#8) OPTIONAL "deploy"
#9) OPTIONAL "after_deploy"
#10) "after_script"

# prevent Travis CI from resetting your working directory and deleting all changes made during the build ( git stash --all)
# "deploy:
#   skip_cleanup: true"

# # blocklist
# branches:
#   except:
#   - legacy
#   - experimental
#
# # safelist
# branches:
#   only:
#   - master
#   - stable
#   - /^deploy-.*$/
#   - /^(?i:deploy)-.*$/

# Add "[ci skip]" or "[skip ci]" to git commit message
# to ignore building the commit
