language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-24.0.2
    - android-24

script:
   - ./gradlew build connectedCheck

    # The BuildTools version used by your project
    # - build-tools-19.1.0

    # The SDK version used to compile your project
    # - android-22

    # # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-19
    #
    # # Specify at least one system image,
    # # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-22
    # - sys-img-x86-android-exited with 117


#1) Install "apt addons"
#2) "before_install"
#3) "install"
#4) "before_script"
#5) "script"
#6) "after_success" or "after_failure"
#7) OPTIONAL "before_deploy"
#8) OPTIONAL "deploy"
#9) OPTIONAL "after_deploy"
#10) "after_script"

# prevent Travis CI from resetting your working directory and deleting all changes made during the build ( git stash --all)
# "deploy:
#   skip_cleanup: true"

# # blocklist
# branches:
#   except:
#   - legacy
#   - experimental
#
# # safelist
# branches:
#   only:
#   - master
#   - stable
#   - /^deploy-.*$/
#   - /^(?i:deploy)-.*$/

# Add "[ci skip]" or "[skip ci]" to git commit message
# to ignore building the commit
